const state = {
  dataGoods:[],
  livingRoomList: [],
  currentProduct: {
    art: null,
    category: null,
    description: null,
    id: null,
    img: [null],
    link_name: null,
    name: null,
    number: null,
    price: null,
    price_sale: null,
    recommended: null,
    remark: null,
    stok: null,
    the_height: null,
    the_long: null,
    the_weight: null,
    type: null,
    visible: null,
    param: {
      cabinet_h: null,
      cabinet_w: null,
      cabinet_l: null,
      mat_front: null,
      mat_corp: null,
      made_in: null,
      color: null,
      color_1: null,
      bed_h: null,
      bed_l: null,
      bed_w: null,
      sleeper_w: null,
      sleeper_l: null,
      tumbaTV_h: null,
      tumbaTV_l: null,
      tumbaTV_w: null,
      mirror_l: null,
      mirror_h: null,
      mirror_w: null,
      commode_l: null,
      commode_h: null,
      commode_w: null,
      nightstand_l: null,
      nightstand_h: null,
      nightstand_w: null,
      mattress_w: null,
      mattress_l: null,
    }
  }
};
export default state
